"""restricao_catalogo (restrições padrão)

Revision ID: 0eaac58af528
Revises: 490de1a8a52f
Create Date: 2026-07-25 17:48:08.790941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaac58af528'
down_revision: Union[str, Sequence[str], None] = '490de1a8a52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricao_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_nome', sa.String(length=200), nullable=False),
    sa.Column('unidade_normalizada', sa.String(length=200), nullable=False),
    sa.Column('pavimento_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pavimento_catalogo_id'], ['pavimento_catalogo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_normalizada', 'pavimento_catalogo_id', 'tipo', name='uq_restricao_catalogo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricao_catalogo')
    # ### end Alembic commands ###
