"""esquema inicial do SAA

Revision ID: 490de1a8a52f
Revises: 
Create Date: 2026-07-23 22:33:35.306439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490de1a8a52f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('etapa_atual', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origem_id'], ['alocacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pavimento_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloco', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('padrao_1est', sa.Integer(), nullable=False),
    sa.Column('padrao_2est', sa.Integer(), nullable=False),
    sa.Column('esp_1est', sa.Integer(), nullable=False),
    sa.Column('esp_2est', sa.Integer(), nullable=False),
    sa.Column('fechada', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bloco', 'nome', name='uq_pavimento_catalogo')
    )
    op.create_table('unidade_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=200), nullable=False),
    sa.Column('participa_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_normalizado', name='uq_unidade_catalogo')
    )
    op.create_table('alocacao_etapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_id', 'numero', name='uq_etapa')
    )
    op.create_index(op.f('ix_alocacao_etapa_alocacao_id'), 'alocacao_etapa', ['alocacao_id'], unique=False)
    op.create_table('pavimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('bloco', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('padrao_1est', sa.Integer(), nullable=False),
    sa.Column('padrao_2est', sa.Integer(), nullable=False),
    sa.Column('esp_1est', sa.Integer(), nullable=False),
    sa.Column('esp_2est', sa.Integer(), nullable=False),
    sa.Column('fechada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pavimento_alocacao_id'), 'pavimento', ['alocacao_id'], unique=False)
    op.create_table('alocacao_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('unidade_nome', sa.String(length=200), nullable=False),
    sa.Column('participa', sa.Boolean(), nullable=False),
    sa.Column('pavimento_alocado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pavimento_alocado_id'], ['pavimento.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_id', 'unidade_nome', name='uq_unidade_no_cenario')
    )
    op.create_index(op.f('ix_alocacao_unidade_alocacao_id'), 'alocacao_unidade', ['alocacao_id'], unique=False)
    op.create_table('alocacao_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_unidade_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('qtd_alocada', sa.Integer(), nullable=False),
    sa.Column('qtd_nao_alocada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_unidade_id'], ['alocacao_unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_unidade_id', 'dia_semana', 'turno', name='uq_resultado')
    )
    op.create_index(op.f('ix_alocacao_resultado_alocacao_unidade_id'), 'alocacao_resultado', ['alocacao_unidade_id'], unique=False)
    op.create_table('grade_demanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_unidade_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_unidade_id'], ['alocacao_unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_unidade_id', 'dia_semana', 'turno', name='uq_demanda')
    )
    op.create_index(op.f('ix_grade_demanda_alocacao_unidade_id'), 'grade_demanda', ['alocacao_unidade_id'], unique=False)
    op.create_table('grade_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_unidade_id', sa.Integer(), nullable=False),
    sa.Column('profissional', sa.String(length=200), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('revisar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_unidade_id'], ['alocacao_unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_slot_alocacao_unidade_id'), 'grade_slot', ['alocacao_unidade_id'], unique=False)
    op.create_table('restricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('alocacao_unidade_id', sa.Integer(), nullable=False),
    sa.Column('pavimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alocacao_unidade_id'], ['alocacao_unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pavimento_id'], ['pavimento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_unidade_id', 'pavimento_id', 'tipo', name='uq_restricao')
    )
    op.create_index(op.f('ix_restricao_alocacao_id'), 'restricao', ['alocacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restricao_alocacao_id'), table_name='restricao')
    op.drop_table('restricao')
    op.drop_index(op.f('ix_grade_slot_alocacao_unidade_id'), table_name='grade_slot')
    op.drop_table('grade_slot')
    op.drop_index(op.f('ix_grade_demanda_alocacao_unidade_id'), table_name='grade_demanda')
    op.drop_table('grade_demanda')
    op.drop_index(op.f('ix_alocacao_resultado_alocacao_unidade_id'), table_name='alocacao_resultado')
    op.drop_table('alocacao_resultado')
    op.drop_index(op.f('ix_alocacao_unidade_alocacao_id'), table_name='alocacao_unidade')
    op.drop_table('alocacao_unidade')
    op.drop_index(op.f('ix_pavimento_alocacao_id'), table_name='pavimento')
    op.drop_table('pavimento')
    op.drop_index(op.f('ix_alocacao_etapa_alocacao_id'), table_name='alocacao_etapa')
    op.drop_table('alocacao_etapa')
    op.drop_table('unidade_catalogo')
    op.drop_table('pavimento_catalogo')
    op.drop_table('alocacao')
    # ### end Alembic commands ###
