"""especialidade auditoria e regras padrao

Revision ID: 5b34eae537c0
Revises: 490de1a8a52f
Create Date: 2026-07-24 15:06:53.374810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b34eae537c0'
down_revision: Union[str, Sequence[str], None] = '490de1a8a52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricao_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_unidade', sa.String(length=200), nullable=False),
    sa.Column('unidade_normalizada', sa.String(length=200), nullable=False),
    sa.Column('pavimento_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pavimento_catalogo_id'], ['pavimento_catalogo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_normalizada', 'pavimento_catalogo_id', name='uq_restricao_padrao')
    )
    op.create_index(op.f('ix_restricao_padrao_unidade_normalizada'), 'restricao_padrao', ['unidade_normalizada'], unique=False)
    op.add_column('grade_slot', sa.Column('especialidade', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade_slot', 'especialidade')
    op.drop_index(op.f('ix_restricao_padrao_unidade_normalizada'), table_name='restricao_padrao')
    op.drop_table('restricao_padrao')
    # ### end Alembic commands ###
